version: '3.9'

services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - pictshare
    # Default caddy command borrowed from https://github.com/caddyserver/caddy-docker/blob/master/Dockerfile.tmpl
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--watch"]


  pictshare:
    build:
      context: pictshare
    restart: unless-stopped
    environment:
      HASH_DIMS_AES_KEY: ${HASH_DIMS_AES_KEY}
      CONTENTCONTROLLERS: "IMAGE,VIDEO"
    volumes:
      - pictshare_data:/var/www/data

volumes:
  caddy_data:
  caddy_config:
  pictshare_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: ${DATA_DIR}
